name: Build Dylib
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone fishhook
        run: git clone https://github.com/facebook/fishhook.git
      - name: Compile dylib
        run: |
          clang -arch arm64 \
            -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
            -miphoneos-version-min=13.0 \
            -I./fishhook \
            -dynamiclib \
            -o SpeedHack.dylib \
            SpeedHack.c fishhook/fishhook.c \
            -framework Foundation
      - uses: actions/upload-artifact@v4
        with:
          name: SpeedHackDylib
          path: SpeedHack.dylib
