name: Build Dylib
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone Dobby
        run: git clone https://github.com/jmpews/Dobby.git

      - name: Compile dylib
        run: |
          clang -arch arm64 \
            -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
            -miphoneos-version-min=13.0 \
            -dynamiclib \
            -fobjc-arc \
            -o SpeedHack.dylib \
            SpeedHack.c \
            $(find Dobby/source -name "*.c") \
            -I Dobby/include \
            -framework UIKit -framework Foundation

      - uses: actions/upload-artifact@v4
        with:
          name: SpeedHackDylib
          path: SpeedHack.dylib
